# Generated by Django 4.1.1 on 2022-12-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testuuid",
            name="name",
        ),
        migrations.AlterField(
            model_name="testuuid",
            name="uuid",
            field=models.UUIDField(verbose_name="uuid"),
        ),
    ]
